metadata.format.version = "1.1"

[versions]
gson = "2.13.2"
minecraft = "1.21.11"

slf4j-api = "2.0.17"
logback = "1.5.19"

vanilla-gradle = "0.2.1-SNAPSHOT"
nmcp = "1.2.0"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-api" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[bundles]
logging = ["slf4j-api", "logback-core", "logback-classic"]

[plugins]
vanilla-gradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "vanilla-gradle" }
nmcp = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
